name:                kore
version:             0.0.1.0
github:              "kframework/kore"
license:             NCSA
license-file:        LICENSE
author:              "Virgil Serbanuta"
maintainer:          "virgil.serbanuta@runtimeverification.com"
copyright:           "2018-2019 Runtime Verification Inc"
category:            Language

extra-source-files:
  - README.md
  - ChangeLog.md
  - test/resources/*.kore
  - test/resources/*.kore.golden

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the [README](README.md) file.

dependencies:
  - base >= 4.7
  - array
  - bytestring >= 0.10
  - comonad
  - containers >= 0.5.8
  - clock
  - co-log
  - cryptonite
  - data-default
  - deepseq
  - directory
  - errors
  - exceptions
  - extra
  - fgl
  - free
  - filepath
  - generic-lens
  - generics-sop
  - ghc-trace-events
  - gitrev
  - graphviz
  - groom
  - hashable
  - haskeline
  - integer-gmp
  - lens
  - megaparsec >= 7.0.4
  - memory
  - mmorph
  - mtl
  - optparse-applicative
  - parser-combinators
  - prettyprinter
  - process
  - profunctors
  - recursion-schemes
  - reflection
  - semialign
  - template-haskell
  - text
  - these
  - time
  - transformers
  - unliftio-core
  - unordered-containers

build-tools:
  - tasty-discover

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingVia
  - DuplicateRecordFields
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns

ghc-options: -fno-ignore-asserts

library:
  source-dirs: src

executables:
  kore-parser:
    main: Main.hs
    source-dirs:
      - app/parser
      - app/share
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -A32M -qn8"
    dependencies:
      - kore

  kore-exec:
    main: Main.hs
    source-dirs:
      - app/exec
      - app/share
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -A32M -qn8"
    dependencies:
      - kore

  kore-format:
    main: Main.hs
    source-dirs:
      - app/format
      - app/share
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -A32M -qn8"
    dependencies:
      - kore

  kore-repl:
    main: Main.hs
    source-dirs:
      - app/repl
      - app/share
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -A32M -qn8"
    dependencies:
      - kore

  kore-profiler:
    main: Main.hs
    source-dirs:
      - app/profiler
      - app/share
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -A32M -qn8"
    dependencies:
      - kore

tests:
  kore-test:
    main: Test.hs
    source-dirs:
      - test
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -A32M -qn8"
    dependencies:
      - kore
      - call-stack
      - directory >= 1.2.2
      - filepath
      - hedgehog
      - QuickCheck
      - quickcheck-instances
      - tasty
      - tasty-ant-xml
      - tasty-hedgehog
      - tasty-hunit
      - tasty-golden
      - tasty-quickcheck
      - template-haskell

benchmarks:
  kore-parser-benchmark:
    main: Main.hs
    other-modules:
      - Paths
    source-dirs:
      - bench/parser
      - test
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -A32M -qn8"
    dependencies:
      - kore
      - criterion
      - directory >= 1.2.2
      - filepath
      - template-haskell

  kore-exec-benchmark:
    main: Main.hs
    other-modules:
      - Paths
    source-dirs:
      - bench/exec
      - test
    ghc-options: -threaded -rtsopts "-with-rtsopts=-N -A32M -qn8"
    dependencies:
      - kore
      - criterion
      - directory >= 1.2.2
      - filepath
      - process
      - template-haskell
      - temporary
