# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# This file contains a template configuration file, which is typically
# placed as .hlint.yaml in the root of your project


# Specify additional command line arguments
#
# - arguments: [--color, --cpp-simple, -XQuasiQuotes]
- arguments: [-XTypeApplications]


# Control which extensions/flags/modules/functions can be used
#
# - extensions:
#   - default: false # all extension are banned by default
#   - name: [PatternGuards, ViewPatterns] # only these listed extensions can be used
#   - {name: CPP, within: CrossPlatform} # CPP can only be used in a given module
#
# - flags:
#   - {name: -w, within: []} # -w is allowed nowhere
#
# - modules:
#   - {name: [Data.Set, Data.HashSet], as: Set} # if you import Data.Set qualified, it must be as 'Set'
#   - {name: Control.Arrow, within: []} # Certain modules are banned entirely
#
# - functions:
#   - {name: unsafePerformIO, within: []} # unsafePerformIO can only appear in no modules


# Add custom hints for this project
#
# Will suggest replacing "wibbleMany [myvar]" with "wibbleOne myvar"
# - error: {lhs: "wibbleMany [x]", rhs: wibbleOne x}


# Turn on hints that are off by default
#
# Ban "module X(module X) where", to require a real export list
# - warn: {name: Use explicit module export list}
#
# Replace a $ b $ c with a . b $ c
# - group: {name: dollar, enabled: true}
#
# Generalise map to fmap, ++ to <>
# - group: {name: generalise, enabled: true}


# Ignore some builtin hints
# - ignore: {name: Use let}
# - ignore: {name: Use const, within: SpecialModule} # Only within certain modules

# Corporate style
- ignore: {name: "Use tuple-section"}
- ignore: {name: "Use record patterns"}
- ignore: {name: "Use String"}
- ignore: {name: "Redundant id"}

# Eta reduction can impact readability significantly.
- ignore: {name: Eta reduce}

# Permit existing duplication in tests.
# Please reflect before adding new modules to this list.
- ignore:
    name: Reduce duplication
    within:
      - Test.Kore
      - Test.Kore.AllPath
      - Test.Kore.ASTVerifier.DefinitionVerifier.Imports
      - Test.Kore.Builtin.Definition
      - Test.Kore.Builtin.List
      - Test.Kore.Builtin.Map
      - Test.Kore.Builtin.Set
      - Test.Kore.Internal.TermLike
      - Test.Kore.Parser.Parser
      - Test.Kore.Repl.Interpreter
      - Test.Kore.Step.Step
      - Test.Kore.Step.Substitution

# The placement of lambdas affects inlining.
- ignore: {name: Redundant lambda}

# Testing class laws
- ignore: {name: Use <$>, within: [Test.Data.Sup, Test.ListT]}
- ignore: {name: Functor law, within: [Test.Data.Sup, Test.ListT]}
- ignore: {name: Use /=, within: [Test.Data.Sup]}
- ignore: {name: "Monad law, left identity", within: [Test.ListT]}
- ignore: {name: "Monad law, right identity", within: [Test.ListT]}
- ignore: {name: "Use >=>", within: [Test.ListT]}
- ignore: {name: "Redundant id", within: [Test.ListT]}

- ignore: {name: Use camelCase, within: [Test.Terse]}

# Unsuitable suggestions
- ignore:
    name: "Reduce duplication"
    within:
      - Kore.Builtin.Builtin
      - Kore.Builtin.List
      - Kore.Domain.Builtin
      - Kore.Exec
      - Kore.Internal.Conditional
      - Kore.Step.Simplification.AndTerms
      - Kore.Parser.Parser
- ignore: {name: "Use fmap", within: [Kore.Step.Step]}
- ignore:
    name: "Use <$>"
    within:
      - Kore.Parser.Parser
      - Kore.Step.Step

# Haskell names match K names
- ignore:
    name: "Use camelCase"
    within:
      - Kore.Builtin.MapSymbols
      - Kore.Debug

- ignore: {name: "Use newtype instead of data", within: [GlobalMain]}

- ignore: {name: "Redundant compare", within: [Kore.Syntax.Id]}


# Define some custom infix operators
# - fixity: infixr 3 ~^#^~


# To generate a suitable file for HLint do:
# $ hlint --default > .hlint.yaml
